Conan V2 basic support
artipie/conan-adapter pull request #10
Opened 2021-07-21 10:09 UTC by ChGen

Base class for Conan V2 API handlers + Readme update.
Issue: #2

2021-07-21 10:14 UTC, ChGen commented
@olenagerasimova , please review.

2021-07-21 11:44 UTC, olenagerasimova approved these changes
@ChGen thanks, just one minor comment

2021-07-21 11:44 UTC, olenagerasimova commented on README.md
> +Conan client uses V1 API by default, as its more stable. Anyway, both V1 and V2 APIs aren't public, so they could change. The conan_server supports both APIs by default.
> as **its** more stable

Seems like should be _it's_

2021-07-21 12:38 UTC, ChGen commented on README.md
> +Conan client uses V1 API by default, as its more stable. Anyway, both V1 and V2 APIs aren't public, so they could change. The conan_server supports both APIs by default.
Yes, thanks!

2021-07-21 14:54 UTC, olenagerasimova approved these changes
@ChGen thanks

2021-07-22 06:35 UTC, g4s8 requested changes
@ChGen please check my comments. Also, I don't really understand why do we need this pull-request - it's some implementation details for objects which doesn't exist yet. I'd suggest going from up to down: first add some entry-points/HTTP-endpoints/etc with stubs, and then implement deeper and deeper all missed objects, and apply refactoring on demand (don't start with refactoring). Right now we have some implementation details which is not connected to anything (no users of this class), so it's hard to understand how exactly it will work, and it has a risk to be rewritten from scratch in case if it doesn't suite for Conan-adapter design.

2021-07-22 08:20 UTC, ChGen commented
I tried to split changes on smaller parts, but it wasn't very efficient. I'll put the rest today for review, for broader picture.

2021-07-22 11:37 UTC, ChGen commented
@g4s8 , please review with full set of changes.

2021-07-28 11:28 UTC, g4s8 requested changes
@ChGen review comments on code are still valid after new changes, please address them

2021-08-04 13:41 UTC, ChGen commented on src/main/java/com/artipie/conan/http/BaseConanSlice.java
> +abstract class BaseConanSlice implements Slice {
BaseConanSlice holds common functionality of Conan protocol V2 slices. V1 part will be refactored to support it too, so this base class will be extended a bit further. I think switching to composition will make things more verbose, also it will require updating all slices.

2021-08-04 13:43 UTC, ChGen commented on src/main/java/com/artipie/conan/http/BaseConanSlice.java
> +                            StandardRs.NOT_FOUND,
I think PUT/POST will be processed differently.

2021-08-04 13:44 UTC, ChGen commented on src/main/java/com/artipie/conan/http/BaseConanSlice.java
> +    public Storage getStorage() {
Agree, it should be protected.

2021-08-04 13:44 UTC, ChGen commented on src/main/java/com/artipie/conan/http/BaseConanSlice.java
> +    public PathWrap getPathWrap() {
Agree, it should be protected.

2021-08-04 13:47 UTC, ChGen commented on src/main/java/com/artipie/conan/http/BaseConanSlice.java
> +        private final byte[] data;
Currently data is read from Storage in async/non-blocking manner, after that it could be later parsed in some way (e.g. as Json object). As for ResponseResult object, it could be created if several ways, not always with async-producing source.

2021-08-04 13:49 UTC, ChGen commented on src/main/java/com/artipie/conan/http/BaseConanSlice.java
> +            this(data.getBytes(StandardCharsets.UTF_8), "application/json");
ResponseResult class could be created if several ways, with various possible content types.

2021-08-04 17:39 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/BaseConanSlice.java
> +            return this.data == null || this.data.length == 0;
@ChGen this comment is not fixed

2021-08-13 11:58 UTC, ChGen commented
some thenApply() chanages are in refactoring branch.

2021-08-13 12:00 UTC, ChGen commented
@g4s8 , please review. The rest in the new pull request:
https://github.com/artipie/conan-adapter/pull/12

2021-08-17 08:17 UTC, g4s8 approved these changes
@ChGen thanks

2021-08-17 08:17 UTC, merged