@ChGen Revisions index prototype.
artipie/conan-adapter pull request #11
Opened 2021-07-30 13:09 UTC by ChGen

Revisions index basic support for future SDK use. Here is package recipe index support, package binary index is WIP.

2021-07-30 13:09 UTC, ChGen commented
@olenagerasimova , please review.

2021-07-30 14:48 UTC, olenagerasimova requested changes
@ChGen please, take a look at my comments. There is one huge problem: we have no idea if any line of this code works, as there is no tests.

2021-07-30 14:48 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +    public CompletionStage<Void> addRecipeRevision(final Integer revision) {
@ChGen why are you using `Integer` instead of `int`? If null is possible, I've already mentioned that nulls are not allowed

2021-07-30 14:48 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +            .thenCompose(
No need for `thenCompose`, use `thenApply`

2021-07-30 14:48 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +    public CompletionStage<Boolean> removeRecipeRevision(final Integer revision) {
Same comment about `Integer`

2021-07-30 14:48 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +                                            rev, checks.stream().allMatch(CompletableFuture::join)
Do not call `join()` or other blocking methods in the main code

2021-07-30 14:48 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +                        nothing -> revs.stream().filter(tuple -> tuple.join()._2())
Same here - do not call `join()` or other blocking methods in the main code

2021-07-30 14:48 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +    private CompletableFuture<Boolean> removeRevision(final Integer revision, final String path) {
why use `Integer` instead of `int` as a parameter?

2021-07-30 14:48 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +                .thenCompose(nothing -> CompletableFuture.completedFuture(true));
use `thenApply` here instead of `thenCompose`

2021-07-30 14:48 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +    private static JsonObject newRevision(final Integer revision) {
use `int` as parameter type

2021-07-30 14:48 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/BaseConanSlice.java
> +            content.thenCompose(
use `thenApply` here instead of `thenCompose `

2021-07-30 14:48 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> + * @checkstyle ClassDataAbstractionCouplingCheck (999 lines)
Generally, in the most cases, high DAC [means](https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/checks/metrics/ClassDataAbstractionCouplingCheck.html) that class has too complex structure. It's recommended to refactor all the classes, where we have, for some reasons, to suppress this check and do not tolerate such suppression in the new code.

2021-08-04 05:57 UTC, ChGen commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +                                            rev, checks.stream().allMatch(CompletableFuture::join)
Here I'm collecting results from multiple CompletableFuture's after execution CompletableFuture.allOf(), so *.join() won't block current thread.

2021-08-04 06:17 UTC, ChGen commented on src/main/java/com/artipie/conan/http/BaseConanSlice.java
> +            content.thenCompose(
I will fix it as part of the HTTP layer update.

2021-08-04 09:50 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +                                            rev, checks.stream().allMatch(CompletableFuture::join)
There is still a way to avoid using blocking calls (we do not use them in the main code, tests only), as far as I understand, what you generally need is a map of key and existence indicating boolean, here is the example:
```
final List<Key> keys = new ListOf<Key>(new Key.From("one"), new Key.From("two"));
CompletionStage<List<Tuple2<Key, Boolean>>> res = Flowable.fromIterable(keys).flatMapSingle(
    key -> Single.fromFuture(this.storage.exists(key).thenApply(exists -> new Tuple2<>(key, exists)))
).toList().to(SingleInterop.get())
```

2021-08-04 09:52 UTC, olenagerasimova commented
@ChGen I've answered to your comment about `join()` calls, also, I do not see any fixes...

2021-08-06 06:07 UTC, ChGen commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +                                            rev, checks.stream().allMatch(CompletableFuture::join)
Thank you, but it doesn't look clearer, so I'd prefer to use .allOf() + .join() solution, if join() isn't strictly prohibited per se.

2021-08-06 06:08 UTC, ChGen commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> + * @checkstyle ClassDataAbstractionCouplingCheck (999 lines)
I agree. I'll think on refactoring this as the next step, most probably.

2021-08-06 06:09 UTC, ChGen commented
Added package binary supporting code, code review fixes and tests.

2021-08-06 06:09 UTC, ChGen commented
@olenagerasimova , please review.

2021-08-06 06:46 UTC, olenagerasimova requested changes
@ChGen added several comments, please, take a look

2021-08-06 06:46 UTC, olenagerasimova commented on src/test/java/com/artipie/conan/RevisionsIndexTest.java
> +    void recipeInfoTest() {
do not use word `Test` if the test method's names, as this word is absolutely redundant, we already know it's a test as a) this class is in the test scope b) the class name ends with `Test`. Test method names should be normal english sentences that shows what the test object can or cannot, for example: `canProvideRecipeRevision`. Read [this](https://www.yegor256.com/2014/04/27/typical-mistakes-in-java-code#test-method-names), also do not forget about [single statement in the tests](https://www.yegor256.com/2017/05/17/single-statement-unit-tests.html) and take a look at the typical [mistakes](https://www.yegor256.com/2018/12/11/unit-testing-anti-patterns.html)

2021-08-06 06:46 UTC, olenagerasimova commented on src/test/java/com/artipie/conan/RevisionsIndexTest.java
> +            ).toCompletableFuture().join();
formatting is off

2021-08-06 06:52 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +                                            rev, checks.stream().allMatch(CompletableFuture::join)
for me it looks much clearer and more readable, but it's the matter of taste and habit. Also, `Puple2` is not really needed here, I'd prefer `Map`. Ok, I leave it to @g4s8

2021-08-12 09:13 UTC, g4s8 requested changes
@ChGen please check my comments, this PR needed to be refactored, I'd suggest closing it, refactor and submit by smaller parts, it leads to better decomposition and understanding of each part.

2021-08-12 09:13 UTC, g4s8 commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +     * Creates path to the binary revisions file. Should be private later.
What are the reasons to make it public now?

2021-08-12 09:13 UTC, g4s8 commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +    public String getBinaryRevpath(final int reciperev, final String hash) {
Is it a `Key` or file `Path`? Let's use correct abstraction here

2021-08-12 09:13 UTC, g4s8 commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +    public CompletionStage<Void> fullIndexUpdate() {
Are you sure that all these methods are needed to be included into initial version of SDK?

2021-08-12 09:13 UTC, g4s8 commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +                    .sequential().observeOn(Schedulers.io());
What is the reason of changing downstream execution thread if we don't have any downstream here?

2021-08-12 09:13 UTC, g4s8 commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +    private static <T> CompletableFuture<List<T>> fromFlowable(final Flowable<T> flowable) {
This method could be replaced with standard `flowable.toList().to(CompletableInterop.await())`

2021-08-12 09:13 UTC, g4s8 commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +                            .filter(rev -> rev >= 0).collect(Collectors.toSet()).stream().map(
Double streaming is redundant here: keys to stream then back to collection, then back to stream

2021-08-12 09:13 UTC, g4s8 commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +                                            rev, checks.stream().allMatch(CompletableFuture::join)
@ChGen please don't use `join()` in production code

2021-08-12 09:13 UTC, g4s8 commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +    private CompletableFuture<List<Integer>> buildIndex(final String path, final String[] pkgfiles,
This method is very hard to read, consider refactoring

2021-08-12 09:13 UTC, g4s8 commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +public final class RevisionsIndex {
This class is too big and complex, please split it to multiple smaller classes with reduced scope of responsibilities to continue review. Right now, it's very hard to understand the purpose of this PR.

2021-08-17 08:35 UTC, closed without merging