Conan V1 protocol refactoring, with some V2 changes.
artipie/conan-adapter pull request #12
Opened 2021-08-13 11:57 UTC by ChGen

Conan V1 protocol refactoring, with some V2 changes. 2 commits from V2 protocol branch.

2021-08-13 12:01 UTC, ChGen commented
@g4s8 , please review, - this is based on prvious PR https://github.com/artipie/conan-adapter/pull/10

2021-08-17 08:50 UTC, ChGen commented
Rebased on master.

2021-08-23 07:36 UTC, g4s8 requested changes
@ChGen please check my comments

2021-08-23 07:36 UTC, g4s8 commented on src/main/java/com/artipie/conan/http/ConansEntity.java
> +                            String.format(
You can use `UriBuilder` https://docs.oracle.com/javaee/7/api/javax/ws/rs/core/UriBuilder.html here instead of string formatting: it'll validate all parts of URI and automatically escape some characters

2021-08-23 07:36 UTC, g4s8 commented on src/main/java/com/artipie/conan/http/ConansEntity.java
> +                                ConansEntity.URL_FMT, ConansEntity.PROTOCOL, hostname, tuple._1()
Same here: `UriBuilder`

2021-08-23 07:36 UTC, g4s8 commented on src/main/java/com/artipie/conan/http/ConansEntity.java
> +                }, str -> String.join("", "{", str, "}")
And again: why not `JsonObjectBuilder`?

2021-08-23 07:36 UTC, g4s8 commented on src/main/java/com/artipie/conan/http/ConansEntity.java
> +        private static String getQuestion(final RequestLineFrom request) {
You can use `RqParams` class to parse request query params instead of this method

2021-08-23 07:36 UTC, g4s8 commented on src/main/java/com/artipie/conan/http/ConansEntityV2.java
> +        return String.join(
Same here: why string joining and not `JsonObjectBuilder`?

2021-08-24 13:56 UTC, ChGen commented
@g4s8 , please review.

2021-08-30 06:27 UTC, ChGen commented on src/main/java/com/artipie/conan/http/ConansEntityV2.java
> +                    return result;
For those responses I have to provide filename as the key and value as empty string. Empty optional means that file doesn't exist, so it won't be included in the response json.

2021-08-30 06:27 UTC, ChGen commented on src/main/java/com/artipie/conan/http/ConansEntityV2.java
> +                    return result;
For those responses I have to provide filename as the key and value as empty string. Empty optional means that file doesn't exist, so it won't be included in the response json.

2021-08-30 10:33 UTC, ChGen commented
@g4s8 , please review, I rebased on master, added one new commit.

2021-08-30 12:34 UTC, g4s8 approved these changes
@ChGen thanks

2021-08-30 12:34 UTC, merged