Completables
artipie/conan-adapter pull request #13
Opened 2021-08-17 12:23 UTC by ChGen

Classes for Collecting results from multiple CompletableFutures. They will be used in both, SDK & Protocol parts, and keep join()-s and unchecked casts in single place.
Note that in this push request CompletableFuture.join() won't block, since it's used after CompletableFuture.allOf().

At first I implemented it as utility class, but then I found out that it's prohibited by qulice, so I ended up implementing it as several classes.
I keep original implementation in the first commit for the reference.

2021-08-17 12:27 UTC, ChGen commented
@olenagerasimova , please review.

2021-08-17 12:57 UTC, olenagerasimova commented
@ChGen I cannot agree with using `join` in the main code as a) it's not really necessary, I've [written](https://github.com/artipie/conan-adapter/pull/11#discussion_r682463885) an example with rx java without `joins` b) @g4s8 also [asked](https://github.com/artipie/conan-adapter/pull/11#discussion_r687531976) not to call `join()` in production code

I will review this PR only if @g4s8 agrees with using joins, otherwise it's a waste of time.

2021-08-18 07:21 UTC, g4s8 commented
> @ChGen I cannot agree with using `join` in the main code as a) it's not really necessary, I've [written](https://github.com/artipie/conan-adapter/pull/11#discussion_r682463885) an example with rx java without `joins` b) @g4s8 also [asked](https://github.com/artipie/conan-adapter/pull/11#discussion_r687531976) not to call `join()` in production code
> 
> I will review this PR only if @g4s8 agrees with using joins, otherwise it's a waste of time.

@olenagerasimova @ChGen as we discussed previously, `join()` could be used after `CompletableFuture.allOf(array)` call (`allOf` returns `CompletableFuture<Void>`), because `allOf` guarantees that all futures will be completed before `join()` call - in that case `join()` is not a blocking call, it's just a result accessor. But in that case, I think we need to hide this login inside a new class, and make this class responsible for calling `allOf` before `join`

2021-08-18 07:30 UTC, ChGen commented
This is one of the goals of this PR - provide special classes, that hide that logic.

2021-08-18 07:39 UTC, olenagerasimova requested changes
@ChGen please check comments

2021-08-18 07:39 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/Completables.java
> +            @SuppressWarnings("rawtypes") final CompletableFuture[] arr = futures
variable `arr` is redundant

2021-08-18 07:39 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/Completables.java
> +            @SuppressWarnings("rawtypes") final CompletableFuture[] arr = futures
same here, `arr` is redundant

2021-08-18 09:12 UTC, ChGen commented on src/main/java/com/artipie/conan/Completables.java
> +            @SuppressWarnings("rawtypes") final CompletableFuture[] arr = futures
I could remove `arr`, but it will be required to move `@SuppressWarnings("rawtypes")` to function header. For this small function it could be even better, but I still would like to clarify.

2021-08-18 09:12 UTC, ChGen commented on src/main/java/com/artipie/conan/Completables.java
> +            @SuppressWarnings("rawtypes") final CompletableFuture[] arr = futures
I could remove `arr`, but it will be required to move `@SuppressWarnings("rawtypes")` to function header. For this small function it could be even better, but I still would like to clarify.

2021-08-18 09:13 UTC, ChGen commented
@olenagerasimova , please respond.

2021-08-18 10:09 UTC, olenagerasimova approved these changes
@ChGen ok, good for me

2021-08-18 12:02 UTC, ChGen commented
@olenagerasimova , please review.

2021-08-18 12:20 UTC, olenagerasimova approved these changes

2021-08-18 13:32 UTC, g4s8 requested changes
@ChGen looks good. But I have some design comments: it's not clear from names what these classes are doing, e.g. `new Completables.ForList().toList()`, maybe we can use another name, like `Join` or `Merge` to describe that this class is joining or merging the result of provided futures? Another question is: why do we need two different classes here?  It seems we can just provide two (or more) secondary constructors of one class: `ForList(List<CompletableFuture<T>>)`, `ForList(List<Tuple2<K, CompletableFuture<V>>>)` (in second case `T` will be `Tuple<>`.

2021-08-18 14:03 UTC, ChGen commented
@g4s8 , concerning naming, I actually like `Join` option, like `new Completables.JoinList().toList()`,  `new Completables.JoinTuples().toTuples()`. 
As for the merging two classes with <T>, I think it will be harder to extract required fields and also we will lose some type checking precision during usage with `Tuple`, since there are two different generic types, Key and Value in the `Tuple`, and Value is wrapped inside CompletableFuture in the input.

2021-08-18 15:02 UTC, g4s8 commented
> @g4s8 , concerning naming, I actually like `Join` option, like `new Completables.JoinList().toList()`, `new Completables.JoinTuples().toTuples()`.
> As for the merging two classes with , I think it will be harder to extract required fields and also we will lose some type checking precision during usage with `Tuple`, since there are two different generic types, Key and Value in the `Tuple`, and Value is wrapped inside CompletableFuture in the input.

@ChGen I see, so let's use two classes

2021-08-19 07:09 UTC, ChGen commented
@g4s8 , please review.

2021-08-19 08:47 UTC, g4s8 approved these changes
@ChGen thanks

2021-08-19 08:48 UTC, merged