Basic RevisionsIndex support.
artipie/conan-adapter pull request #15
Opened 2021-08-27 08:03 UTC by ChGen

Part of #5  - provides basic support of Conan package revisions (V2 API) for Artipie SDK.

2021-08-30 08:39 UTC, ChGen commented
@olenagerasimova , please review.

2021-08-30 09:23 UTC, olenagerasimova requested changes
@ChGen thanks, check my comments please, mostly about tests

2021-08-30 09:23 UTC, olenagerasimova commented on src/test/java/com/artipie/conan/RevisionsIndexTest.java
> +        new TestResource("conan-test/data").addFilesTo(this.storage, Key.ROOT);
please, do not add anything into storage on setup even more so you remove items in the begining of the test

2021-08-30 09:23 UTC, olenagerasimova commented on src/test/java/com/artipie/conan/RevisionsIndexTest.java
> +        this.storage.delete(new Key.From(RevisionsIndexTest.ZLIB_BIN_INDEX)).join();
same here, do not add anything on setup and do not remove it in the beginning of the test

2021-08-30 09:23 UTC, olenagerasimova commented on src/test/java/com/artipie/conan/RevisionsIndexTest.java
> +            "Checking revision object fields are correct",
Assertion messages should be grammaticality correct English sentences, they should describe what is expected:
"Http status 201 CREATED is returned"
"Height of tested `Table` object is 2 meters" 
etc

2021-08-30 11:34 UTC, ChGen commented on src/test/java/com/artipie/conan/RevisionsIndexTest.java
> +        this.storage.delete(new Key.From(RevisionsIndexTest.ZLIB_SRC_INDEX)).join();
> 
> 
> @ChGen thanks, check my comments please, mostly about tests

@olenagerasimova , the idea is that I have full set of valid conan package files for repository, and for some tests (like indexing tests) I will remove this specific file, for another - I won't remove it, but maybe I'll do something else for preparation. So here in the test I explicitly remove index file and it must be recreated by indexing code.

2021-08-30 11:53 UTC, olenagerasimova commented on src/test/java/com/artipie/conan/RevisionsIndexTest.java
> +        this.storage.delete(new Key.From(RevisionsIndexTest.ZLIB_SRC_INDEX)).join();
@ChGen seems like you need several test methods for the cases you are describing. One method - for the empty repository, second - for not empty, add indexes only when necessary. For example, check [this](https://github.com/artipie/conda-adapter/pull/47/files) PR - I add index files when it's necessary and name test methods accordingly, thus it is obvious for the reader what is going on in the test.

2021-08-31 07:22 UTC, ChGen commented on src/test/java/com/artipie/conan/RevisionsIndexTest.java
> +        this.storage.delete(new Key.From(RevisionsIndexTest.ZLIB_SRC_INDEX)).join();
@olenagerasimova , so using  `@BeforeEach void setUp() { ... }` to prepare files in storage considered as bad practice, and `@ParameterizedTest @CsvSource({"path/to/file1", "path/to/file2"})` is considered good practice. Am I correct?

2021-08-31 09:43 UTC, olenagerasimova commented on src/test/java/com/artipie/conan/RevisionsIndexTest.java
> +        this.storage.delete(new Key.From(RevisionsIndexTest.ZLIB_SRC_INDEX)).join();
> so using @BeforeEach void setUp() { ... } to prepare files in storage

is not a bad practice if files you are adding to storage are required in EACH test method. Adding files to storage in `@BeforeEach void setUp() { ... }` that are NOT required in EACH test method of the test class does not make any sense (to me). 

`@ParameterizedTest` can be used when necessary, but it has nothing to do with adding any files into storage in `@BeforeEach` method.

2021-08-31 09:45 UTC, olenagerasimova commented on src/test/java/com/artipie/conan/RevisionsIndexTest.java
> +        this.storage.delete(new Key.From(RevisionsIndexTest.ZLIB_SRC_INDEX)).join();
`@BeforeEach void setUp() { ... }` simply allows avoiding repeating storage initialization at the beginning of each test method, that all.

2021-08-31 10:21 UTC, ChGen commented on src/test/java/com/artipie/conan/RevisionsIndexTest.java
> +        this.storage.delete(new Key.From(RevisionsIndexTest.ZLIB_SRC_INDEX)).join();
@olenagerasimova , so here I should do preparation of storage in each test separately, with adding only required files, and not removing extra from full set, right?

2021-08-31 10:23 UTC, olenagerasimova commented on src/test/java/com/artipie/conan/RevisionsIndexTest.java
> +        this.storage.delete(new Key.From(RevisionsIndexTest.ZLIB_SRC_INDEX)).join();
yes, sure

2021-09-02 10:26 UTC, ChGen commented
@olenagerasimova , please review.

2021-09-03 08:28 UTC, olenagerasimova requested changes
@ChGen please, check my comment. If you do not agree, please, consult Kirill

2021-09-03 08:28 UTC, olenagerasimova commented on src/test/java/com/artipie/conan/RevisionsIndexTest.java
> +        }
I'm very confused, what was in the previous iteration:
1) you added some files to storage in the `@BeforeEach` method
2) then you REMOVED some of them (unnecessary ones I assumed) in the tests

My comment was: do not add these files in `@BeforeEach` method, add only required items to storage ones in each test method. Thus there should not be ANY extra (not required) items in the storage while each test method is performed. 

Now the same set of items is put to storage in each test method... Why have you removed some items in the previous version? 

The main point here is that unit tests should be as simple as possible, they should not share any data, contain extra data etc. Why? Because it can lead to false positive/negative effects. Let's say you test class, which builds repository metadata file. You add to storage packages and metadata file, just because this file is in the same test resource directory and is required in another test method. Then you write test, which tests that this metadata file was build. You will never know whether this file was actually build, or it's the same file you put to the storage at the beginning of the test method.

Also, it would be better not to use same resource (in our case I think not to use metadata files specifically, packages examples (in my opinion) can be reused as they never change and are not generated by our code) in different tests, as it might be necessary to change this resource with some fix or new feature development and thus all other tests will be broken.

2021-09-03 13:11 UTC, ChGen commented on src/test/java/com/artipie/conan/RevisionsIndexTest.java
> +        }
@olenagerasimova , thanks for the explanations.

Here’s my general idea: at first I prepared the directory with small set of files corresponding to particular Conan package (server-side layout). Then I add this directory (with all its files) in setup test method and do some extra preparations at the beginning of the tests. For those two tests the preparation action is to remove old (original) index file explicitly, which must be generated by the code “from scratch” later in the test. After running indexing code of `RevisionIndex` class, I load generated file directly and also load its data with `RevisionIndex` class. So I check both, the file itself, directly, and the general functionality of the `RevisionIndex`. 
According to the 1st review, my understanding was that adding files in bulk (from the directory) and explicit (manual) removal isn’t in line with Artipie project style, so I refactored my code to add explicit set of required files, without removals of unnecessary files. So, this time I add explicitly only required files, by full list. ( I mean discussion in https://github.com/artipie/conan-adapter/pull/15#discussion_r698410787 )

Personally, I’d prefer the very first variant, since:
1)	There’s concise set of test files (resources), which are used, no duplication in filesystem and git.
2)	Since they aren’t duplicated, its clear that they are really the same, for all affected tests.
3)	In case of test data changes, you don’t have to check/change all similar subdirectories with test data.
4)	Explicit file removals in the tests are balanced, paired with explicit file load of the same file, after execution of `RevisionIndex` logic. So in case of this file is missing I’d get test fail.
5)	Explicit file removal with subsequent usage in those tests also demonstrates dynamics of the events and relevance of this specific file in those particular tests. 
6)	`RevisionIndex` logic results are tested too and also compared to direct read from json file.
7)	No extra explicit enumeration of file names is required in the code or some other file.

2021-09-03 13:11 UTC, ChGen commented on src/test/java/com/artipie/conan/RevisionsIndexTest.java
> +        }
@g4s8 , Kirill, please review too :)

2021-09-03 13:42 UTC, olenagerasimova commented on src/test/java/com/artipie/conan/RevisionsIndexTest.java
> +        }
I still do not understand why add files to the storage and remove them. What is the exact reason for these operation? Always add the same files to the storage at the beginning of each test? I also do not see any reason for that as each test case checks different scenarion. 

Also, it would be very easy to forget to remove some files for the new person in project, which can lead to false-positive effect.

2021-09-03 14:03 UTC, ChGen commented on src/test/java/com/artipie/conan/RevisionsIndexTest.java
> +        }
In this tests (original revision), removing specific file at the beginning of the test allows us to keep common set of test files more simple. The removal by path is paired with subsequent loading by path, so we check the result of the indexing too (in addition to using `RevisionIndex` logic). Keeping common set of test file in simple form shows that for all related tests the same (literally) set of files are used, reduces amounts of potential changes of test data updates, reduces duplication in FS/VCS. I see all this as advantages too.

2021-09-06 08:49 UTC, g4s8 requested changes
@ChGen please check my comments

2021-09-06 08:49 UTC, g4s8 commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +                    "", path, "/", rev.toString(), "/", RevisionsIndex.SRC_SUBDIR, "/", name
It seems you can join in `"/"` here

2021-09-06 08:49 UTC, g4s8 commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +        );
And same here:
```suggestion
        final String path = String.join(
            "/", this.pkg, Integer.toString(reciperev),
            RevisionsIndex.BIN_SUBDIR, hash
        );
```

2021-09-06 08:49 UTC, g4s8 commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +     * Extracts revisions list for provided storage key path and list of its keys.
This comment is not clear

2021-09-06 08:49 UTC, g4s8 commented on src/main/java/com/artipie/conan/RevisionsIndex.java
> +                    result = -1;
Why do we need to return `-1` here? You can just filter out these value using `filter()`

2021-09-06 08:49 UTC, g4s8 commented on src/test/java/com/artipie/conan/RevisionsIndexTest.java
> +        }
I agree with @olenagerasimova - no need to copy resource to delete it later, we can just copy only minimal required set of resources for each test

2021-09-06 09:38 UTC, ChGen commented on src/test/java/com/artipie/conan/RevisionsIndexTest.java
> +        }
@g4s8  @olenagerasimova , at this iteration I don't delete files and copy them by explicit list. Is it solution good enough? Or maybe it's better to have a copy of directory and don't use explicit list of filenames?

2021-09-06 10:00 UTC, olenagerasimova commented on src/test/java/com/artipie/conan/RevisionsIndexTest.java
> +        }
@ChGen if these files are really required in the test method and do not overlap with items created by the tested functionality, then yes, it's ok

2021-09-06 13:22 UTC, ChGen commented
@g4s8 , please review.

2021-10-04 10:54 UTC, g4s8 requested changes
@ChGen please check my comments regarding tests

2021-10-04 10:54 UTC, g4s8 commented on src/test/java/com/artipie/conan/RevisionsIndexTest.java
> +            "Checking that parsed revision object fields have correct format",
It's assertion message which is shown on test failure, so it'd logical to say here
> Object fields have incorrect format

2021-10-04 10:54 UTC, g4s8 commented on src/test/java/com/artipie/conan/RevisionsIndexTest.java
> +            "Checking that revision object fields have correct values",
And same here. Also, I'd be more concrete, e.g. use "revision is not correct". And split this check onto two different assertions: first for revision and second for time.

2021-10-04 12:52 UTC, ChGen commented
@g4s8 , please review.

2021-10-04 13:11 UTC, g4s8 commented
@ChGen please update this PR according to https://github.com/artipie/artipie/blob/master/CONTRIBUTING.md (add PR description and linked ticket) and we're ready for merge

2021-10-04 13:30 UTC, ChGen commented
@g4s8 , updated my PR.

2021-10-04 14:02 UTC, ChGen commented
@olenagerasimova , please review.

2021-10-04 14:13 UTC, olenagerasimova approved these changes

2021-10-04 14:13 UTC, merged

2021-10-06 08:33 UTC, g4s8 commented
@ChGen fixed commit message in master

2021-10-06 10:24 UTC, ChGen commented
@g4s8 , thanks!