Revision index - other APIs
artipie/conan-adapter pull request #21
Opened 2021-11-03 13:11 UTC by ChGen

Here's Revision index extra APIs with tests.

2021-11-03 13:24 UTC, ChGen commented
@olenagerasimova , please review.

2021-11-08 06:35 UTC, olenagerasimova requested changes
@ChGen thanks, just one minor comment. Also, it seems like `RevisionsIndexApi` class gets bigger and bigger, is it possible to divide it somehow? Cohesion also does not look good, for example, only one new method from 11 uses `RevisionsIndexer` field...

2021-11-08 06:35 UTC, olenagerasimova commented on src/test/java/com/artipie/conan/RevisionsIndexApiTest.java
> +            ).toCompletableFuture().join();
formatting here is off

2021-11-08 09:30 UTC, ChGen commented
@olenagerasimova , please review.
In the current APIs `FullIndexer` is used once and `RevisionsIndexer` is used twice (for recipes and binaries) + referenced in `FullIndexer`. This is the last subtle set of changes for Revision index part, so my current plan is to keep the API in single interface for now, as is, and in the future refactor both indexers out of the main interface, so it will be smaller and with better cohesion.

2021-11-08 09:40 UTC, olenagerasimova approved these changes
@ChGen ok, thanks

2021-11-08 09:54 UTC, merged