Updated documentation for Conan Adapter
artipie/conan-adapter pull request #22
Opened 2021-11-11 13:27 UTC by ChGen

Part of #5 - provides FullIndexer class with tests for Artipie SDK.

2021-11-12 06:57 UTC, g4s8 requested changes
@ChGen please check my comments

2021-11-12 06:57 UTC, g4s8 commented on README.md
> +(`rpm-repo` in our example) and instruct `Rpm` to update the meta info:
@ChGen why RPM here?

2021-11-12 06:57 UTC, g4s8 commented on README.md
> +After that, you can use existing `com.artipie.asto.Storage` implementations to create required storage object.
It'd be good to add a link to asto repo documentation

2021-11-12 06:57 UTC, g4s8 commented on README.md
> +CompletionStage<List<Integer>> getBinaryRevisions(final int reciperev, final String hash);
This should be wrapped with markdowns code format symbols (tripple `)

2021-11-12 06:57 UTC, g4s8 commented on README.md
> +CompletionStage<Void> fullIndexUpdate()
And same here (formatting)

2021-11-12 06:57 UTC, g4s8 commented on README.md
> +See also Artipie Conan adapter javadoc.
You can add a link to auto-generated HTML javadocs here (see javadoc badges in other repos to get thelink)

2021-11-12 07:38 UTC, ChGen commented on README.md
> +(`rpm-repo` in our example) and instruct `Rpm` to update the meta info:
@g4s8 , oh, sorry, those training courses made me inattentive, I'll finish with them first :/

2021-11-15 13:23 UTC, ChGen commented
@g4s8 , please review. I added two links also.

2021-11-15 14:08 UTC, g4s8 approved these changes
@ChGen thanks

2021-11-15 14:09 UTC, merged