Basic .ini files support
artipie/conan-adapter pull request #23
Opened 2021-12-10 13:30 UTC by ChGen

Conan repository uses .ini files format internally. Here's basic implementation for .ini reads and writes.

2021-12-10 13:35 UTC, ChGen commented
@g4s8 , please review.

2021-12-10 14:32 UTC, g4s8 requested changes
@ChGen please check my comments

2021-12-10 14:32 UTC, g4s8 commented on pom.xml
> +      <version>0.18.4</version>
`v1.0.1` is available

2021-12-10 14:32 UTC, g4s8 commented on pom.xml
> +      <version>0.5</version>
Is it a compile dependency? Maybe it should be test-scoped?

2021-12-10 14:32 UTC, g4s8 commented on src/main/java/com/artipie/conan/IniFile.java
> +        this(IniFile.loadEntries(new String(data)));
It's not a good practice to perform IO operations in constructor since class user may not expect such a delay during construction

2021-12-10 14:32 UTC, g4s8 commented on src/main/java/com/artipie/conan/IniFile.java
> +    public <T> T getValue(final String section, final String key, final T defaultvalue) {
I'm not sure about this design: why do we need to create some objects in runtime here, is it really init file loader responsibility? Maybe we can return just a string here (because ini file is a string-based)?

2021-12-10 14:32 UTC, g4s8 commented on src/test/java/com/artipie/conan/IniFileTest.java
> +    }
No need to create temp file manually, just add `Path` paramenter to method with `@TempDir` junit annotation:
```java
void testMethod(@TempDir Path tmp) {
```

2021-12-13 10:50 UTC, ChGen commented on pom.xml
> +      <version>0.18.4</version>
@g4s8 , for 1.0.1 version I have an error that it doesn't exist. Do I have to add some extra mirror?

2021-12-13 10:50 UTC, ChGen commented on pom.xml
> +      <version>0.5</version>
Agree, thanks!

2021-12-13 11:01 UTC, ChGen commented on src/main/java/com/artipie/conan/IniFile.java
> +        this(IniFile.loadEntries(new String(data)));
@g4s8 , OTOH, loading behavior is described explicitly in the javadoc.
As for this exact signature, it loads the contents from the byte array in the memory, so probably I should wrap the exception in the Artipie exception, since it's won't be real IO exception here, strictly speaking.

2021-12-13 11:05 UTC, ChGen commented on src/main/java/com/artipie/conan/IniFile.java
> +    public <T> T getValue(final String section, final String key, final T defaultvalue) {
@g4s8 , this is convenience method, which allows to use it with simpler logic, so we could just provide default value of required basic type and get the result in this form. There's also simpler, getString() version. Probably I should clarify javadoc & add test cases for this.

2021-12-13 11:11 UTC, ChGen commented on src/test/java/com/artipie/conan/IniFileTest.java
> +    }
@g4s8 , this annotation is allowed for `Path` & `File` types, but fills it with already created temporary directory. So to create some file there, extra code is required anyway. Since there's no annotation for the temporary file, I'd prefer to keep current version.

2021-12-13 11:15 UTC, ChGen commented on src/main/java/com/artipie/conan/IniFile.java
> +        this(IniFile.loadEntries(new String(data)));
In my code, I will use IniFile(final byte[]) signature mostly, since all in is async. via Artipie framework classes.

2021-12-14 05:53 UTC, g4s8 commented on pom.xml
> +      <version>0.18.4</version>
No mirror needed. Maybe the problem is that we switched to semantic versioning template which includes `v` as a part of version name, so the dependency is `<version>v1.0.1</version>`

2021-12-14 05:55 UTC, g4s8 commented on src/main/java/com/artipie/conan/IniFile.java
> +        this(IniFile.loadEntries(new String(data)));
I see, then it's not possible that byte-buffer array throws IOException here, right? So we can wrap it with some `UncheckedIOException` and remove from method signature

2021-12-14 05:58 UTC, g4s8 commented on src/test/java/com/artipie/conan/IniFileTest.java
> +    }
Standard `File.write` operation (without additional flags provided) will create file if it doesn't exist, so you can just use:
```java
@Test
void testMethod(@TempDir Path tmp) {
  new IniFile(tmp.resolve("file.ini"));
}
```

2021-12-14 06:02 UTC, g4s8 commented on src/main/java/com/artipie/conan/IniFile.java
> +        this(IniFile.loadEntries(new String(Files.readAllBytes(Paths.get(path)))));
Second constructor is OK, but this one has a problem: performing blocking IO operation in constructor is a bad-practice since it makes object creation time unpredictable and error prone. Also, it's confusing that both constructors similar signature (`byte[]` and `String`). I'd suggest making a static method for reading from file and providing `Path` as parameter instead of `String`: `InitFile.loadFile(Path)`

2021-12-14 06:06 UTC, g4s8 commented on src/main/java/com/artipie/conan/IniFile.java
> +    public <T> T getValue(final String section, final String key, final T defaultvalue) {
I see, but it's very not obvious that `T` class must have a constructor for string. It'd be much better if you use some factory to construct the value: `<T> T getValue(String section, String key, Function<String, ? extends T> factory)` - in this case the user have to explicitly specify how to construct the object from string.

2021-12-14 12:31 UTC, ChGen commented on src/main/java/com/artipie/conan/IniFile.java
> +        this(IniFile.loadEntries(new String(Files.readAllBytes(Paths.get(path)))));
@g4s8 , now it turns out that according to qulice, public static methods are prohibited. So it looks like if I think this functionality is useful, I still have to keep it in constructor....

2021-12-14 14:12 UTC, g4s8 commented on src/main/java/com/artipie/conan/IniFile.java
> +        this(IniFile.loadEntries(new String(Files.readAllBytes(Paths.get(path)))));
Qulice is just a code-style checker, the common sense is more important here: we assume that constructors are fast and safe, so we can use it without inspecting dependency code

2021-12-14 14:51 UTC, ChGen commented on src/main/java/com/artipie/conan/IniFile.java
> +        this(IniFile.loadEntries(new String(Files.readAllBytes(Paths.get(path)))));
@g4s8 , okay, I'll keep as static. It's just that in Yegor articles there's lots of critics for statics, but not much about its constructor requirements.

2021-12-15 09:05 UTC, ChGen commented on pom.xml
> +      <version>0.5</version>
Actually, it is used in Conan Cli utility for 'VertxSliceServer' class.

2021-12-15 09:06 UTC, ChGen commented on src/main/java/com/artipie/conan/IniFile.java
> +    public <T> T getValue(final String section, final String key, final T defaultvalue) {
Updated implementation

2021-12-15 09:09 UTC, ChGen commented on src/main/java/com/artipie/conan/IniFile.java
> +        this(IniFile.loadEntries(new String(Files.readAllBytes(Paths.get(path)))));
Keep it 'static' now, with warning suppression. But I don't see why documented IO (long) behaviour in constructor is worse than statics (which are 'bad practice' for the current code style)

2021-12-15 09:13 UTC, ChGen commented on src/test/java/com/artipie/conan/IniFileTest.java
> +    }
Here java.lang.IllegalStateException: the temporary folder has not yet been created

2021-12-15 09:28 UTC, ChGen commented on src/test/java/com/artipie/conan/IniFileTest.java
> +    }
For this, I added "@SuppressWarnings("PMD.ProhibitFilesCreateFileInTests")" due to Qulice complains, maybe there's problem in Qulice since @TempDir marked as added in junit 5.4 and as an experimental. 
I'll try to use suggested by Qulice "@Rule TemporaryFolder", but I get an error in the tests: "java.lang.IllegalStateException: the temporary folder has not yet been created"

2021-12-15 09:29 UTC, ChGen commented
@g4s8 , please review, I updated the code & the comments above.

2021-12-15 12:45 UTC, ChGen commented on src/main/java/com/artipie/conan/IniFile.java
> +    public <T> T getValue(final String section, final String key, final T defaultvalue) {
For this, I incline to have both, concise version, and version with external factory. I think concise version is quite convenient, but needs clear description in javadoc.

2021-12-15 13:17 UTC, g4s8 approved these changes
@ChGen thanks

2021-12-15 13:18 UTC, merged