Conan users API - minimal support for uploads.
artipie/conan-adapter pull request #24
Opened 2022-01-17 06:02 UTC by ChGen

Part of #2 - provides Conan users API minimal support, required for package uploads.

2022-01-17 06:29 UTC, ChGen commented
@g4s8 , please review.
Also, Maven Build / pdd-linter is failing at the moment for its own reasons.

2022-01-18 06:25 UTC, olenagerasimova requested changes
@ChGen thanks, please, check my comments

2022-01-18 06:25 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/UsersEntity.java
> +                            if (Strings.isNullOrEmpty(content)) {
hm, content equals `{}`, so this condition will always be false...

2022-01-18 06:25 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/UsersEntity.java
> +                    uri -> CompletableFuture.completedFuture("{}").thenCompose(
I'd suggest to use `thenApply` instead of `thenCompose` here, then directly `Response` can be returned instead of completable future with response

2022-01-18 06:25 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/UsersEntity.java
> +                    uri -> CredsCheck.credsCheck().thenCompose(
same here, use `thenApply` and return `Response`

2022-01-18 06:25 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/UsersEntity.java
> +            return CompletableFuture.completedFuture("{}");
will this method be re-implemented somehow later?

2022-01-18 06:25 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/UsersEntity.java
> +                                result = new RsWithHeaders(
use `RsJson` here, it will add all necessary headers and charset

2022-01-18 06:25 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/UsersEntity.java
> +                                result = new RsWithHeaders(
use `RsJson` here, it will add all necessary headers and charset

2022-01-18 07:35 UTC, ChGen commented on src/main/java/com/artipie/conan/http/UsersEntity.java
> +            return CompletableFuture.completedFuture("{}");
Yes, later it will be extended futher, to provide broader set of Conan HTTP APIs.

2022-01-18 07:36 UTC, ChGen commented on src/main/java/com/artipie/conan/http/UsersEntity.java
> +                            if (Strings.isNullOrEmpty(content)) {
I've fixed it similar to credsCheck(). Later it will be extended further, to provide broader set of Conan HTTP APIs.

2022-01-18 07:37 UTC, ChGen commented on src/main/java/com/artipie/conan/http/UsersEntity.java
> +                                result = new RsWithHeaders(
For error message I don't return Json now, so I'd prefer to keep this part 'as is'.

2022-01-18 07:37 UTC, ChGen commented on src/main/java/com/artipie/conan/http/UsersEntity.java
> +                                result = new RsWithHeaders(
For error message I don't return Json now, so I'd prefer to keep this part 'as is'.

2022-01-18 08:27 UTC, ChGen commented
@olenagerasimova , please review.

2022-01-18 09:55 UTC, olenagerasimova approved these changes
@ChGen thanks

2022-01-19 12:10 UTC, g4s8 approved these changes
@ChGen thanks, I think we need integration test for Conan upload here

2022-01-19 12:11 UTC, merged

2022-01-19 13:23 UTC, ChGen commented
@g4s8 , I plan to add integration tests as a next step after finishing with working upload sequence. Should I add Unit Tests for Slices (requests) classes first?