Extra requests for Conan package uploads
artipie/conan-adapter pull request #26
Opened 2022-01-19 07:01 UTC by ChGen

Part of #2 - implements extra requests, required for Conan package uploads. 1 new commit.

2022-01-19 07:29 UTC, ChGen commented
@olenagerasimova , please review.

2022-01-19 09:17 UTC, olenagerasimova requested changes
@ChGen thanks, one comment. And again - there are no unit tests

2022-01-19 11:46 UTC, ChGen commented
please, review.As for tests, here's mainly http requests for Conan client, so there will be integration tests later. Probably as part of the main Artipie project.

2022-01-19 12:16 UTC, ChGen commented
@olenagerasimova, please, review. 
As for tests, here's mainly http requests for Conan client, so there will be integration tests later. I think they will be part of the main Artipie project repo.

2022-01-19 12:47 UTC, olenagerasimova requested changes
One more suggestion, also, I did not ask about ITs, I've asked about unit tests. Each adapter have unit test for each slice, there are not many exceptions.

2022-01-19 12:47 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/BaseConanSlice.java
> +                                }
there also is a `Digests` enum in `asto`, use `MD5` constant

2022-01-20 06:20 UTC, olenagerasimova requested changes
@ChGen one more suggestion

2022-01-20 06:20 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/BaseConanSlice.java
> +                        });
the expression can be simplified to 
```
result = this.storage.value(key).thenCompose(contente -> new ContentDigest(content, Digests.MD5).hex())
```

2022-01-20 07:16 UTC, ChGen commented
@olenagerasimova , please review.

2022-01-20 08:26 UTC, olenagerasimova approved these changes
@ChGen thanks

2022-01-26 14:29 UTC, merged