Basic uploading support
artipie/conan-adapter pull request #27
Opened 2022-01-28 14:02 UTC by ChGen

Basic support for uploading of packages from the Conan client.

2022-01-28 14:20 UTC, ChGen commented
@olenagerasimova , please review.

2022-01-28 14:35 UTC, olenagerasimova requested changes
@ChGen thanks, check several comments please

2022-01-28 14:35 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/ConanUpload.java
> +        matcher.matches();
I'd suggest to whether `matcher.matches()` returned true and throw an exception if not.

2022-01-28 14:35 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/ConanUpload.java
> +                    final StringBuilder result = new StringBuilder("{");
hm, there is `javax.json` library to build jsons, use `JsonBuilber`

2022-01-28 14:35 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/ConanUpload.java
> +                    return (Response) new RsWithHeaders(
if json will be build properly as json object, then it will be very convenient to use RsJson here:
```
return new RsJson(result)
```
Headers will be added by `RsJson` class

2022-01-31 10:57 UTC, ChGen commented on src/main/java/com/artipie/conan/http/ConanUpload.java
> +                    return (Response) new RsWithHeaders(
Here I can't use RsJson, since it produces string with encoding info, like "application/json; charset=UTF-8", which is not accepted by Conan client.

2022-01-31 10:58 UTC, ChGen commented
@olenagerasimova , please review.

2022-01-31 14:56 UTC, olenagerasimova approved these changes
@ChGen thanks, looks good to me
@g4s8 take a look please

2022-01-31 15:14 UTC, ChGen commented
What happened with this "Maven Build / pdd-linter (pull_request)" ?

2022-02-02 13:09 UTC, merged