Conan upload urls test
artipie/conan-adapter pull request #28
Opened 2022-02-03 10:30 UTC by ChGen

Unit test for UploadUrls slice.

2022-02-03 10:30 UTC, ChGen commented
@olenagerasimova , please review.

2022-02-03 11:07 UTC, olenagerasimova requested changes
@ChGen thanks, check my suggestions please

2022-02-03 11:07 UTC, olenagerasimova commented on src/test/java/com/artipie/conan/http/ConanUploadUrlsTest.java
> +                    )))
closing brackets are not properly formatted in this part of code, correct, please

2022-02-03 11:07 UTC, olenagerasimova commented on src/test/java/com/artipie/conan/http/ConanUploadUrlsTest.java
> +            new RsHasBody(
I'd suggest also to check response status, this could be done with the help of `RsHasStatus` matcher:
```
Matchers.allOf(
    new RsHasStatus(...),
    new RsHasBody(...)
)
```
Headers (if necessary) can be checked in the same way.

2022-02-03 11:07 UTC, olenagerasimova commented on src/test/java/com/artipie/conan/http/ConanUploadUrlsTest.java
> +        final Response response = new ConanUpload.UploadUrls(storage).response(
`response`, `path` and `storage` variables are redundant and can inlined

2022-02-03 12:04 UTC, ChGen commented
@olenagerasimova , please review.

2022-02-04 06:53 UTC, olenagerasimova approved these changes
@ChGen approving, though redundant variables were not inlined

2022-02-07 14:05 UTC, merged