Tests for current user check requests
artipie/conan-adapter pull request #32
Opened 2022-02-07 06:05 UTC by ChGen

Tests for current user check requests.

2022-02-07 06:10 UTC, ChGen commented
@olenagerasimova , please review.

2022-02-07 07:09 UTC, olenagerasimova requested changes
@ChGen thanks, please, check my suggestions

2022-02-07 07:09 UTC, olenagerasimova commented on src/test/java/com/artipie/conan/http/UsersEntityTest.java
> +        final Response response = new UsersEntity.UserAuth(storage).response(
these three variables are redundant and can be inlined in both tests methods

2022-02-07 07:09 UTC, olenagerasimova commented on src/test/java/com/artipie/conan/http/UsersEntityTest.java
> +            ), null
Headers creation can be simplified to `new Headers.From("Host", "localhost")` in both tests

2022-02-07 07:09 UTC, olenagerasimova commented on src/test/java/com/artipie/conan/http/UsersEntityTest.java
> +            new RequestLine("GET", path, "HTTP/1.1").toString(),
`RequestLine` has more convenient ctor with two parameters: `RqMethod method` (enum) and `String uri`
```
new RequestLine(RqMethod.GET, "/v1/users/authenticate").toString()
```

2022-02-07 09:38 UTC, ChGen commented
@olenagerasimova , please review.

2022-02-07 11:36 UTC, olenagerasimova submitted a review, later dismissed
@ChGen thanks

2022-02-08 12:06 UTC, ChGen commented
@g4s8 , please review.

2022-02-16 09:09 UTC, g4s8 approved these changes

2022-02-16 09:09 UTC, merged