Updated readme
artipie/conan-adapter pull request #35
Opened 2022-06-21 13:39 UTC by ChGen

Updated readme to include common information in the Artipie. Also, I tried to use badge for link to Telegramm chat.

2022-06-21 15:05 UTC, olenagerasimova requested changes
@ChGen thanks, check my comments please

2022-06-21 15:05 UTC, olenagerasimova commented on README.md
> +
As far as understand, the idea is for each Aritpie repository has exactly the same header and badges set:

<img width="756" alt="image" src="https://user-images.githubusercontent.com/14931449/174831879-dc1c1273-923a-471b-a7c1-d37af0f9da63.png">

So, I'd suggest to copy all the badges (along with their formatting) from, for example, [vertx-server](https://github.com/artipie/vertx-server) (it already has been updated).

2022-06-21 15:05 UTC, olenagerasimova commented on README.md
> +Artipie [roadmap](https://github.com/orgs/artipie/projects/3).
also, we have two sentences for telegram and roadmap:

> If you have any question or suggestions, do not hesitate to create an issue or contact us in
[Telegram](https://t.me/artipie). Artipie [roadmap](https://github.com/orgs/artipie/projects/3).

I'd suggest to add this info somewhere at the beginning

2022-06-22 08:02 UTC, ChGen commented
@olenagerasimova , please review

2022-06-22 14:00 UTC, olenagerasimova requested changes
@ChGen your suggestion about telegram icon was approved, please, copy readme header from this [comment](https://github.com/artipie/artipie/issues/1031#issuecomment-1163026586)

2022-06-23 07:40 UTC, olenagerasimova approved these changes
@ChGen thanks

2022-06-23 07:40 UTC, merged