Conan repository description
artipie/conan-adapter pull request #4
Opened 2021-04-16 07:13 UTC by ChGen

Here's initial information on Conan repository internals & structure.

2021-04-16 08:04 UTC, g4s8 requested changes
@ChGen please check my comments and questions

2021-04-16 08:04 UTC, g4s8 commented on README.md
> +* When accepting repository changes it builds for multiple popular configurations before code review
@ChGen where the actual build happens? Could you please describe a workflow of working with repository? If I understand correctly it is (please fix me if I'm wrong):
 1. Client prepare build recipes (Makefiles, Conan `.py` scripts, CMake scripts)
 2. Client builds binaries and upload to dedicated? server (not same as Conan repository server?)
 3. Client uploads package metadata to Conan repository server
 4. Server regenerates repository metadata by merging new package

2021-04-16 08:04 UTC, g4s8 commented on README.md
> +* Every artifact recipe contains simple executable test project, which is also used for build & packaging checks
@ChGen Does Conan repo perform some tests and builds?

2021-04-16 08:04 UTC, g4s8 commented on README.md
> +* Conan provides its own server on Python. SSL/https and authentication is supported but not required. https://docs.conan.io/en/latest/uploading_packages/running_your_server.html
@ChGen it looks like a proxy for remote Conan repository

2021-04-16 08:04 UTC, g4s8 commented on README.md
> +* Binary artifacts repository for every artifact stores archived source code and multiple pre-built packages with its built configuration in specified text format (conaninfo.txt)
@ChGen if Conan repo and binary repo are different server, does Conan repo know about location of binary repo?

2021-04-16 08:47 UTC, ChGen commented on README.md
> +* Basic configuration options: OS (Windows/Linux/macOS), architecture, compiler, static/shared mode, debug/release mode. https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.htm
Its about structure of the Conan recipe (artifact) configuration(s). I will clarify it in the next commit.

2021-04-16 08:49 UTC, ChGen commented on README.md
> +* Conan uses Python scripts with some base classes provided by Conan project, which wrap steps like patch/configure/make/install, as well as dependencies configuration.
They are executed server side (when checking recipe or preparing binary artifacts) and client side, when preparing package or when binary package is missing for client's configuration.

2021-04-16 08:50 UTC, ChGen commented on README.md
> +* Makefile/Automake and CMake are supported well by Conan python framework, custom builds could also be implemented manually. https://docs.conan.io/en/latest/reference/build_helpers.html
It is related to conan recipe (artifact). Every artifact can have multiple configurations.

2021-04-16 08:51 UTC, ChGen commented on README.md
> +* When accepting repository changes it builds for multiple popular configurations before code review
I'll describe it in the next commit

2021-04-16 08:52 UTC, ChGen commented on README.md
> +* Every artifact recipe contains simple executable test project, which is also used for build & packaging checks
Yes, Conan repo (in wider term) performs test builts & test run before manual reviewing & merging recipes.

2021-04-16 08:53 UTC, ChGen commented on README.md
> +* Conan provides its own server on Python. SSL/https and authentication is supported but not required. https://docs.conan.io/en/latest/uploading_packages/running_your_server.html
In a way, yes.

2021-04-16 08:55 UTC, ChGen commented on README.md
> +* Binary artifacts repository for every artifact stores archived source code and multiple pre-built packages with its built configuration in specified text format (conaninfo.txt)
I think their test servers know about both servers & repos, since they perform different checks, builds & synchronization.

2021-04-19 06:53 UTC, g4s8 approved these changes
@ChGen thanks, looks good

2021-04-19 06:53 UTC, merged