Ech dev
artipie/conan-adapter pull request #6
Opened 2021-04-26 07:14 UTC by ChGen

Initial commit - added some basic files.
API is in ConanRepo class.

2021-04-28 06:17 UTC, g4s8 requested changes
@ChGen please check my comment. When you add the parent pom into your `pom.xml`, it will enable some checkstyle and PMD linters, configures deploy, test and other phases. To check that build is OK, you can check it with `mvn verify -Pqulice`

2021-04-28 06:17 UTC, g4s8 commented on pom.xml
> +
@ChGen please use parent `pom` as `com.artipie/ppom` where all common configuration and plugins are defined, e.g. see https://github.com/artipie/maven-adapter/blob/master/pom.xml#L27

2021-04-28 06:21 UTC, g4s8 commented
@ChGen also, I'd recommend enabling CI on first commit, you can take it from other repositories, e.g. Maven: https://github.com/artipie/maven-adapter/blob/master/.github/workflows/ci-checks.yml and put into `.github/workflows` directory

2021-04-29 14:00 UTC, g4s8 requested changes
@ChGen thanks, please see my comments. Also, please check our contributing guides: https://github.com/artipie/conan-adapter/blob/master/CONTRIBUTING.md

2021-06-01 05:56 UTC, ChGen commented on .github/workflows/ci-checks.yml
> +        java: [11, 13]
1.8 support was added.

2021-06-01 07:36 UTC, g4s8 requested changes
@ChGen thanks for PR! Please check a few comments from me

2021-06-01 07:36 UTC, g4s8 commented on pom.xml
> +      <version>0.17.7</version>
You can use `1.1.0` version

2021-06-01 07:36 UTC, g4s8 commented on src/main/java/com/artipie/conan/ConanRepo.java
> +    public Storage getStorage() {
Why do we need this method?

2021-06-01 07:36 UTC, g4s8 commented on src/main/java/com/artipie/conan/ConanRepo.java
> +    public ConanRepoConfig getConfig() {
Why do we need this method?

2021-06-01 07:36 UTC, g4s8 commented on src/main/java/com/artipie/conan/ConanRepoConfig.java
> +public class ConanRepoConfig {
What is the configuration of Conan repo? I'd remove it for now until we need a separate class for configuration

2021-06-01 07:36 UTC, g4s8 commented on src/main/java/com/artipie/conan/ConanRepo.java
> +public class ConanRepo {
This class could be `final` to avoid unexpected modification from outside the project

2021-06-01 07:36 UTC, g4s8 commented on src/main/java/com/artipie/conan/http/ConanUpload.java
> +    public Storage getAsto() {
Why do we need this method?

2021-06-01 07:36 UTC, g4s8 commented on src/main/java/com/artipie/conan/http/ConanUpload.java
> +    public ConanRepo getRepo() {
Why do we need this method?

2021-06-01 07:36 UTC, g4s8 commented on src/test/java/com/artipie/conan/CliTest.java
> +    void setUp() {
I'd remove empty methods - junit doesn't require these methods to be present in test case

2021-06-01 07:36 UTC, g4s8 commented on src/test/java/com/artipie/conan/CliTest.java
> +    void tearDown() {
And same here

2021-06-01 07:36 UTC, g4s8 commented on src/test/java/com/artipie/conan/http/ConanSliceTest.java
> +    private static final Vertx VERTX = Vertx.vertx();
We usually design our tests in this way:
 - Adapter repository has unit tests against `Slice` object by constructing requests in code and verifying responses using Hamcrest matchers (library). For instance look at this test for RPM: https://github.com/artipie/rpm-adapter/blob/master/src/test/java/com/artipie/rpm/http/RpmUploadTest.java
 - Main artipie/artipie repository has integration tests with Docker and test-cotnainers (lib) against adapter using real HTTP requests or using CLI tools for interacting with repository HTTP endpoints

Some old adapters used to test HTTP endpoints through Vertx server, but now we're tending to remove such tests by replacing with first option. So here, I'd remove Vertx dependency and use pure `Slice` objects with Hamcrest matchers and supplementary testing objects from artipie/http package: https://github.com/artipie/http/tree/master/src/main/java/com/artipie/http/hm

2021-06-01 07:36 UTC, g4s8 commented on pom.xml
> +      <scope>test</scope>
Are you sure we need testcontainers dependency for this adapter?

2021-06-01 12:26 UTC, ChGen commented on src/main/java/com/artipie/conan/ConanRepoConfig.java
> +public class ConanRepoConfig {
Without getter Qulice checker show errors about making variables local (and something else sometimes, too).

2021-06-01 12:27 UTC, ChGen commented on src/main/java/com/artipie/conan/ConanRepo.java
> +public class ConanRepo {
Ok

2021-06-01 12:27 UTC, ChGen commented on src/main/java/com/artipie/conan/http/ConanUpload.java
> +    public Storage getAsto() {
Without getter Qulice checker show errors about making variables local (and something else sometimes, too).

2021-06-01 12:27 UTC, ChGen commented on src/main/java/com/artipie/conan/ConanRepoConfig.java
> +public class ConanRepoConfig {
Ok

2021-06-01 12:28 UTC, ChGen commented on src/main/java/com/artipie/conan/http/ConanUpload.java
> +    public ConanRepo getRepo() {
Without getter Qulice checker show errors about making variables local (and something else sometimes, too).

2021-06-01 12:32 UTC, ChGen commented on src/main/java/com/artipie/conan/ConanRepo.java
> +    public Storage getStorage() {
Thanks, I'll update dependencies.

2021-06-01 12:32 UTC, ChGen commented on src/main/java/com/artipie/conan/ConanRepo.java
> +    public ConanRepoConfig getConfig() {
Without getter Qulice checker show errors about making variables local (and something else sometimes, too).

2021-06-01 14:13 UTC, g4s8 commented on src/main/java/com/artipie/conan/http/ConanUpload.java
> +    public Storage getAsto() {
I see, but it looks like a workaround. These methods look not very useful in future as public API contract. I'd suggest suppressing warnings either with `// @checkstyle ErrorName (10 lines)` comment or `@SuppressWarnings("PMD.<error-name>")` annotation (depends on what static analyzer is complaining about it) and remove methods

2021-06-03 07:28 UTC, g4s8 approved these changes
@ChGen thanks

2021-06-03 08:02 UTC, merged