Basic support for "conan get" & "conan download" client commands
artipie/conan-adapter pull request #7
Opened 2021-06-23 15:39 UTC by ChGen

Added basic support for "conan get" & "conan download" client commands.

2021-06-24 06:46 UTC, g4s8 commented
@ChGen please see failed CI checks

2021-06-24 07:31 UTC, olenagerasimova commented
@ChGen checkstyle failed, please, fix all the issues and ping me to review

2021-06-30 09:37 UTC, olenagerasimova requested changes
@ChGen please, check mt comments.

Also, please, read our contribution [guide](https://github.com/artipie/artipie/blob/master/CONTRIBUTING.md) and note, that PR should have 100-200 changed lines. To achieve that, decompose your work and implement everything incrementally.

2021-06-30 09:37 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/ConansEntity.java
> +    private static final Pattern PKG_BIN_INFO_PAT = Pattern.compile(ConansEntity.PKG_BIN_INFO_PATH);
@ChGen these 4 string and patterns could be handled as objects: create as interface with methods to return string and pattern. Then, create an abstract `Wrap` implementation with protected ctor that accepts string path and final implemented methods. Last, create 4 classes for 4 paths that will extend the `Wrap` implementation. 

Such approach will allow getting rid of constants and work with object. As an example, you can check `com.artipie.rpm.TestRpm` in rpm tests.

2021-06-30 09:37 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/ConansEntity.java
> +        private String hostname;
@ChGen seems like this field can be variable, you can pass it to `generateUrlsData` method as a parameter.

2021-06-30 09:37 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/ConansEntity.java
> +            return result.orElseGet(
@ChGen try to avoid composite names for variable is the future, in most cases there is no reason for them, for example:
conaninfo -> info (this repo is all about conan, so word conan here is not really required)
jsonbuilder -> json or builder
pkgpath -> path, we can assume "package" from method name
etc.

You can [read](https://www.yegor256.com/2014/04/27/typical-mistakes-in-java-code#variable-names) what Yegor has to say about this topic.

2021-06-30 09:37 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/ConansEntity.java
> +            return result.orElseGet(
there is no need to fix all the names in the code, this comment is meant for future

2021-06-30 09:37 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/ConansEntity.java
> +            String>> headers, final Publisher<ByteBuffer> body) {
please, do not separate one parameter signature with line break

2021-06-30 09:37 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/ConansEntity.java
> +                    );
formatting here is not correct, it's odd that check style has passed here

2021-06-30 09:37 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/ConansEntity.java
> +                o -> {
what is `o`? Please, rename it properly. For unused lambdas `ignored` or `nothing` are preferred

2021-06-30 09:37 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/ConansEntity.java
> +                    );
Please, name lambda parameters properly

2021-06-30 09:37 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/ConansEntity.java
> +                );
it's very odd that checkstyle is not complaining about string concatenation, please, use `String.format()` all over the code

2021-06-30 09:37 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/ConansEntity.java
> +                pkghash = null;
Nulls are not allowed, we do not use them, we can only deal with nulls from external libraries. Do not return null from methods, no not assign null. Use `Optional`, but only in the cases when it is really necessary.

2021-06-30 09:39 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/ConansEntity.java
> +    private static final Pattern PKG_BIN_INFO_PAT = Pattern.compile(ConansEntity.PKG_BIN_INFO_PATH);
there is no need to correct it now, you can add todo and do it later. We use [pdd](https://www.yegor256.com/2010/03/04/pdd.html) (both pdd approach and bot to report issues from puzzles) in Artpie.

2021-07-02 15:02 UTC, ChGen commented
Fixed most of the issues.

2021-07-05 08:13 UTC, ChGen commented
@olenagerasimova

2021-07-05 08:44 UTC, olenagerasimova requested changes
@ChGen please, check several more comments

2021-07-05 08:44 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/ConansEntity.java
> +        private String hostname;
@ChGen what about this? It's not possible to convert `hostname` into local variable and pass it to `generateUrlsData` method as a parameter?

2021-07-05 08:44 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/ConansEntity.java
> +                            t -> String.format(
please, name lambda parameters `t` properly. By "properly" I mean in correspondence with the checkstyle (any name should be at least 3 chars long) and common sense (name should repel designation and help the reader to understand the code).

2021-07-05 08:44 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/ConansEntity.java
> +                                conaninfo = "";
`IOException` here is thrown in case of some access problems, right? Then it is not correct to catch it and assign empty string to the result, it would be better to throw unchecked exception (we have `ArtipieIOException` for such cases).

2021-07-05 08:44 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/ConansEntity.java
> +                            if (pkginfo == null) {
Once again, nulls are not allowed in our code, such checks can be made only with the result from external libraries.

2021-07-05 08:44 UTC, olenagerasimova commented on src/main/java/com/artipie/conan/http/PathWrap.java
> +    public static final class PkgBinInfoPath extends PathWrap {
I'd say that word "path" is not needed in each subclass name as the main class already has "path" in its name, you will always refer any subclass as `SearchPkgPath.PathWrap`, `SearchPkg.PathWrap` is shorter and the reader still understands that `SearchPkg` is a path wrap.

2021-07-06 04:38 UTC, ChGen commented
@olenagerasimova  Updated branch according to review.

2021-07-06 07:08 UTC, olenagerasimova submitted a review, later dismissed
@ChGen approving, but here is the comment on nulls. Basically, from my experience, null is used in standard dev world in two cases:
- when smth legally (by legally I mean possible according to current upper level or business or common sense logic) is not found/does not exist/absent etc. For these cases we should use `Optional` (as return type/parameter type/field etc), `Optional` tells the reader (and developer) that situation when value is absent might legally happen and is not an error.
- in case of error/not valid case/logically incorrect scenario. In this case, we should throw an exception to transparently indicate the error, not to return null.

I do not insist on fixing current code, that's just an explanation/observation. And here is the [link](https://www.yegor256.com/2014/05/13/why-null-is-bad.html) to Yegor's blog post. Also, I do not if you are aware, but we are trying to write code in compliance with [EO](https://www.yegor256.com/elegant-objects.html) principals.

2021-07-06 07:09 UTC, olenagerasimova commented
@g4s8 please, take a look/merge

2021-07-07 09:25 UTC, g4s8 requested changes
@ChGen thanks, please check my comments. Also, there are some important design issue. We need to provide two deliverables in Conan adapter:
 1. Conan SDK  which works with Conan metadata, some entry point class to process repository items (`ConanRepo`)
 2. Conan HTTP endpoint which uses this SDK to process metadata changes, this endpoint will be integrated to artipie/artipie project

This pull request provides only HTTP layer for Conan repository and performs all metadata management right in place. We need change the design by decomposing metadata processing logic into SDK layer and use this SDK from HTTP layer.

2021-07-07 09:25 UTC, g4s8 commented on src/main/java/com/artipie/conan/http/PathWrap.java
> +public abstract class PathWrap {
Why do we need this class? It seems we can just use `Pattern.compile(path)` instead of this, and access this pattern instead of `PathWrap::getPattern` and use `pattern.toString()` instead of `PathWrap::getPath`.

2021-07-08 13:28 UTC, ChGen commented on src/main/java/com/artipie/conan/http/PathWrap.java
> +public abstract class PathWrap {
Olena suggested this [here  ](https://github.com/artipie/conan-adapter/pull/7#discussion_r661272245) and I desided that it's good thing to try.

2021-07-08 13:37 UTC, ChGen commented on src/main/java/com/artipie/conan/http/ConansEntity.java
> +                        tuple -> tuple._2().join()
In this place specifically, I work with collection of Futures, and few lines before I do CompletableFuture.allOf(), so all of them are finished when `tuple -> tuple._2().join()` is executed.

2021-07-09 06:37 UTC, ChGen commented
@g4s8 , I fixed some of the issues.

2021-07-12 09:06 UTC, g4s8 approved these changes
@ChGen thanks, please continue this PR with refactoring by extracting SDK methods to class working with metadata

2021-07-12 09:07 UTC, merged