Conan client test info
artipie/conan-adapter pull request #8
Opened 2021-07-06 04:57 UTC by ChGen

Info for testing with original conan client, for reference.
Will be removed after implementing full-futured integration tests later.

2021-07-06 05:00 UTC, ChGen commented
@olenagerasimova , please review.

2021-07-06 07:12 UTC, olenagerasimova submitted a review, later dismissed
@ChGen thanks

2021-07-07 06:02 UTC, ChGen commented
@g4s8 , I noticed that pdd github action produces an error (below), but running `pdd` ruby gem locally produces no errors.
"ERROR: conan-test/conan_server-data.tar.gz; puzzle at line #1; invalid byte sequence in UTF-8"

2021-07-07 09:09 UTC, g4s8 requested changes
@ChGen I'd suggest adding this files to `scr/test/resources` to use them from integration tests later. To fix `pdd` you need to exclude the directory with binary files from `pdd` tool, you can do it by updating `.pdd` file in project root with this lines:
```
--exclude path/to/dir
```
you can check this file for reference https://github.com/artipie/artipie/blob/master/.pdd

Docs: https://github.com/cqfn/pdd/#readme

2021-07-07 13:19 UTC, ChGen commented
@g4s8 , please check, looks like all steps are fixed now.

2021-07-09 09:07 UTC, g4s8 requested changes
@ChGen just a minor comment

2021-07-09 09:07 UTC, g4s8 commented on README.md
> +TODO: #1
@ChGen what does this TODO mean?

2021-07-09 10:01 UTC, ChGen commented on README.md
> +TODO: #1
Its required by pdd

2021-07-12 08:12 UTC, g4s8 commented on README.md
> +TODO: #1
@ChGen it's not actually required, you can safely remove these lines

2021-07-12 08:39 UTC, ChGen commented on README.md
> +TODO: #1
@g4s8 , removed the line in the new commit.

2021-07-12 09:04 UTC, g4s8 approved these changes
@ChGen thanks

2021-07-12 09:04 UTC, merged